\subsection{Promise 1: No null pointer dereferences}

%%%

\begin{frame}{Promise 1: No null pointer dereferences}

\begin{block}{Null pointers are useful.}
They can indicate the absence of optional information.\\
They can indicate failures.\\
But they can introduce severe bugs.
\end{block}
\vspace{1em}
\pause
\begin{block}{Rust separates the concept of a pointer from the concept of an\\
		optional or error value.}
	Optional values are handled by \texttt{Option<T>}.\\
  Error values are handled by \texttt{Result<T, E>}.\\
	Many helpful tools to do error handling.
\end{block}

\end{frame}

%%%

\begin{frame}[fragile]{You already saw \texttt{Option<T>}}
\begin{minted}{rust}
fn safe_div(n: i32, d: i32) -> Option<i32> {
    if d == 0 {
        return None;
    }
    Some(n / d)
}
\end{minted}
\pause
But what if you want to return an error, not just \texttt{None}?
\end{frame}

%%%

\begin{frame}[fragile]{There's also \texttt{Result<T, E>}}
\begin{minted}{rust}
enum Result<T, E> {
    Ok(T),
    Err(E)
}
\end{minted}
\end{frame}

%%%

\begin{frame}[fragile]{How to use \texttt{Result}s:}
\begin{minted}{rust}
enum Error {
    DivisionByZero,
}

fn safe_div(n: i32, d: i32) -> Result<i32, Error> {
    if d == 0 {
        return Err(Error::DivisionByZero);
    }
    Ok(n / d)
}
\end{minted}
\pause
It's good practice to define your own error types instead of using strings.
\end{frame}

%%%

\begin{frame}[fragile]{But \texttt{Result} can get tedious...}
\begin{minted}{rust}
fn do_calc() -> Result<i32, String> {
    let a = match do_subcalc1() {
        Ok(val) => val,
        Err(msg) => return Err(msg),
    };
    let b = match do_subcalc2() {
        Ok(val) => val,
        Err(msg) => return Err(msg),
    };
    Ok(a + b)
}
\end{minted}
\end{frame}

%%%

\begin{frame}[fragile]{Ergonomic error handling with the \texttt{try!} macro}
\begin{minted}{rust}
fn do_calc() -> Result<i32, String> {
    let a = try!(do_subcalc1());
    let b = try!(do_subcalc2());
    Ok(a + b)
}
\end{minted}
\pause
Note: Error signature must match!
\end{frame}

%%%

\begin{frame}[fragile]{Mapping Errors}
What if the signature does not match?
\pause
Then we can use map\_err():
\begin{minted}{rust}
fn do_subcalc() -> Result<i32, String> { ... }
fn do_calc() -> Result<i32, Error> {
    let res = do_subcalc();
    let mapped = res.map_err(|msg| {
        println!("Error: {}", msg);
        Error::CalcFailed
    });
    let val = try!(mapped);
    Ok(val + 1)
}
\end{minted}
\end{frame}

%%%

\begin{frame}[fragile]{Mapping Errors: A closer look}
\begin{minted}{rust}
let mapped = res.map_err(|msg| Error::CalcFailed);
\end{minted}
...is the same as...
\begin{minted}{rust}
let mapped = match res {
    Ok(val) => Ok(val),
    Err(msg) => Err(Error::CalcFailed),
}
\end{minted}
\end{frame}

